// src/app/components/sections/about/about.component.ts
import {
  Component,
  type OnInit,
  type AfterViewInit,
  type ElementRef,
  ViewChild,
  Output,
  EventEmitter,
} from "@angular/core"
import { gsap } from "gsap"
import { ScrollTrigger } from "gsap/ScrollTrigger"

gsap.registerPlugin(ScrollTrigger)

interface TimelineItem {
  year: string
  title: string
  description: string
}

interface Skill {
  name: string
  category: string
}

@Component({
  selector: "app-about",
  templateUrl: "./about.component.html",
  styleUrls: ["./about.component.scss"],
})
export class AboutComponent implements OnInit, AfterViewInit {
  @Output() cursorHover = new EventEmitter<boolean>()
  @ViewChild("aboutSection") aboutSection!: ElementRef

  timelineItems: TimelineItem[] = [
    {
      year: "2023",
      title: "Full-stack Developer",
      description: "Specializing in React, Next.js, and Three.js for interactive web experiences",
    },
    {
      year: "2022",
      title: "Crypto Researcher",
      description: "Conducting research on blockchain technologies and cryptocurrency markets",
    },
    {
      year: "2021",
      title: "Web Developer",
      description: "Started journey into web development with focus on frontend technologies",
    },
    {
      year: "2019",
      title: "Aeronautical Engineer",
      description: "Master's degree in Aeronautical Engineering with focus on fluid dynamics",
    },
  ]

  skills: Skill[] = [
    { name: "Angular", category: "Frontend" },
    { name: "React", category: "Frontend" },
    { name: "Next.js", category: "Frontend" },
    { name: "TypeScript", category: "Language" },
    { name: "Three.js", category: "3D" },
    { name: "GSAP", category: "Animation" },
    { name: "Tailwind CSS", category: "Styling" },
    { name: "Node.js", category: "Backend" },
    { name: "Blockchain", category: "Technology" },
    { name: "Crypto Research", category: "Research" },
    { name: "Aeronautical Engineering", category: "Engineering" },
    { name: "UI/UX Design", category: "Design" },
  ]

  constructor() {}

  ngOnInit(): void {}

  ngAfterViewInit(): void {
    this.initAnimations()
  }

  initAnimations(): void {
    // Animate section title
    gsap.from(".about-title", {
      opacity: 0,
      y: 50,
      duration: 0.8,
      scrollTrigger: {
        trigger: this.aboutSection.nativeElement,
        start: "top 80%",
        end: "top 50%",
        scrub: 1,
      },
    })

    // Animate timeline items
    gsap.from(".timeline-item", {
      opacity: 0,
      y: 50,
      stagger: 0.2,
      duration: 0.8,
      scrollTrigger: {
        trigger: ".timeline",
        start: "top 80%",
        end: "top 50%",
        scrub: 1,
      },
    })

    // Animate skills
    gsap.from(".skill-item", {
      opacity: 0,
      scale: 0.8,
      stagger: 0.05,
      duration: 0.5,
      scrollTrigger: {
        trigger: ".skills-container",
        start: "top 80%",
        end: "top 50%",
        scrub: 1,
      },
    })
  }

  onMouseEnter(): void {
    this.cursorHover.emit(true)
  }

  onMouseLeave(): void {
    this.cursorHover.emit(false)
  }
}

<div #aboutSection class="about">
  <div class="container-custom">
    <h2 class="about-title">From Skies to Code</h2>
    
    <div class="about-content">
      <div class="about-text">
        <p>
          My journey from aeronautical engineering to web development has been driven by a passion for innovation and problem-solving across different domains.
        </p>
        
        <p>
          With a master's degree in Aeronautical Engineering and experience in fluid dynamics and aircraft design, I bring a unique analytical perspective to web development.
        </p>
        
        <p>
          I've since transitioned to full-stack development with Angular, React, and Three.js, specializing in interactive web experiences while also conducting research on blockchain technologies and cryptocurrency markets.
        </p>
        
        <a 
          href="/resume.pdf" 
          target="_blank" 
          class="btn btn-outline resume-button"
          (mouseenter)="onMouseEnter()"
          (mouseleave)="onMouseLeave()"
        >
          Download Resume
        </a>
      </div>
      
      <div class="timeline">
        <h3 class="section-subtitle">Experience Timeline</h3>
        
        <div class="timeline-container">
          <ng-container *ngFor="let item of timelineItems">
            <app-timeline-item 
              [year]="item.year"
              [title]="item.title"
              [description]="item.description"
              (cursorHover)="cursorHover.emit($event)"
            ></app-timeline-item>
          </ng-container>
        </div>
      </div>
    </div>
    
    <div class="skills-section">
      <h3 class="section-subtitle">Skills & Expertise</h3>
      
      <div class="skills-container">
        <ng-container *ngFor="let skill of skills">
          <div 
            class="skill-item"
            (mouseenter)="onMouseEnter()"
            (mouseleave)="onMouseLeave()"
          >
            <span class="skill-name">{{ skill.name }}</span>
            <span class="skill-category">{{ skill.category }}</span>
          </div>
        </ng-container>
      </div>
    </div>
  </div>
</div>

// components/sections/about.tsx
"use client"

import { useRef, useEffect } from "react"
import { motion, useInView } from "framer-motion"
import { gsap } from "gsap"
import { ScrollTrigger } from "gsap/dist/ScrollTrigger"
import MagneticButton from "../magnetic-button"

interface TimelineItem {
  year: string
  title: string
  description: string
}

export const About = () => {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: false, amount: 0.2 })
  const timelineRef = useRef(null)

  const timelineItems: TimelineItem[] = [
    {
      year: "2023",
      title: "Full-stack Developer",
      description: "Specializing in React, Next.js, and Three.js for interactive web experiences",
    },
    {
      year: "2022",
      title: "Crypto Researcher",
      description: "Conducting research on blockchain technologies and cryptocurrency markets",
    },
    {
      year: "2020",
      title: "WordPress Freelance",
      description: "Started freelancing with WordPress and basic web development",
    },
    {
      year: "2019",
      title: "Master's in Aeronautics",
      description: "Completed Master's degree in Aeronautical Engineering with focus on fluid dynamics",
    },
  ]

  const skills = [
    "React",
    "Next.js",
    "TypeScript",
    "Three.js",
    "WebGL",
    "Tailwind CSS",
    "Framer Motion",
    "Node.js",
    "Blockchain",
    "Crypto Research",
    "Aeronautical Engineering",
    "UI/UX Design",
  ]

  useEffect(() => {
    if (typeof window !== "undefined") {
      gsap.registerPlugin(ScrollTrigger)

      if (timelineRef.current) {
        gsap.from(".timeline-item", {
          y: 100,
          opacity: 0,
          stagger: 0.2,
          duration: 0.8,
          scrollTrigger: {
            trigger: timelineRef.current,
            start: "top 80%",
            end: "top 30%",
            scrub: 1,
          },
        })
      }
    }
  }, [])

  return (
    <div className="container-custom py-20">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 50 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 50 }}
          transition={{ duration: 0.8 }}
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-8 text-gradient">From Skies to Code</h2>

          <div className="space-y-6 text-silver">
            <p>
              My journey from aeronautical engineering to web development has been driven by a passion for innovation
              and problem-solving across different domains.
            </p>

            <p>
              With a master's degree in Aeronautical Engineering and experience in fluid dynamics and aircraft design, I
              bring a unique analytical perspective to web development.
            </p>

            <p>
              I've since transitioned to full-stack development with React, Next.js, and Three.js, specializing in
              interactive web experiences while also conducting research on blockchain technologies and cryptocurrency
              markets.
            </p>

            <div className="pt-4">
              <MagneticButton>
                <a href="/resume.pdf" target="_blank" rel="noopener noreferrer" className="btn btn-outline">
                  Download Resume
                </a>
              </MagneticButton>
            </div>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 50 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 50 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          <h3 className="text-2xl font-bold mb-8 text-gradient">Skills & Expertise</h3>

          <div className="flex flex-wrap gap-3">
            {skills.map((skill, index) => (
              <motion.div
                key={skill}
                className="px-4 py-2 bg-white/5 rounded-full text-sm"
                initial={{ opacity: 0, y: 20 }}
                animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
                transition={{ duration: 0.5, delay: 0.1 * index }}
              >
                {skill}
              </motion.div>
            ))}
          </div>

          <div className="mt-12" ref={timelineRef}>
            <h3 className="text-2xl font-bold mb-6 text-gradient">Experience Timeline</h3>

            <div className="space-y-8">
              {timelineItems.map((item, index) => (
                <motion.div
                  key={item.year}
                  className="timeline-item p-6 bg-white/5 rounded-xl transform transition-all duration-300 hover:bg-electric-blue/10 hover:-translate-y-2 hover:shadow-lg hover:shadow-electric-blue/20"
                  initial={{ opacity: 0, y: 20 }}
                  animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
                  transition={{ duration: 0.5, delay: 0.3 + index * 0.1 }}
                >
                  <div className="text-electric-blue font-medium mb-1">{item.year}</div>
                  <h4 className="text-xl font-bold mb-2">{item.title}</h4>
                  <p className="text-silver/80">{item.description}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  )
}
